// Catálogo de antibióticos IV con rangos terapéuticos y parámetros de dosificación
export const ANTIBIOTICOS_IV = [
  {
    drug_name: "Vancomicina",
    dose_mg_kg_min: 15,
    dose_mg_kg_max: 20,
    dose_mg_kg_typical: 15,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/6h", "c/8h", "c/12h", "c/24h"],
    default_frequency: "c/12h",
    route: "IV",
    infusion_time: "60-90 min",
    diluent: "SSN 0.9%",
    volume_ml: 250,
    max_dose_g: 4,
    renal_adjustment: true,
    notes: "Monitorear niveles séricos. Ajustar en IR.",
    category: "Glucopéptidos"
  },
  {
    drug_name: "Piperacilina/Tazobactam",
    dose_mg_kg_min: 100,
    dose_mg_kg_max: 300,
    dose_mg_kg_typical: 200,
    dose_unit: "g",
    dose_basis: "mg/kg",
    frequencies: ["c/6h", "c/8h"],
    default_frequency: "c/8h",
    route: "IV",
    infusion_time: "30 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 4.5,
    renal_adjustment: true,
    notes: "Dosis expresada como piperacilina. 4.5 g = pip 4g + taz 0.5g.",
    category: "Penicilinas + IBL"
  },
  {
    drug_name: "Meropenem",
    dose_mg_kg_min: 10,
    dose_mg_kg_max: 40,
    dose_mg_kg_typical: 20,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/6h", "c/8h"],
    default_frequency: "c/8h",
    route: "IV",
    infusion_time: "30 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 2,
    renal_adjustment: true,
    notes: "Dosis alta 40 mg/kg para SNC.",
    category: "Carbapenémicos"
  },
  {
    drug_name: "Imipenem/Cilastatina",
    dose_mg_kg_min: 15,
    dose_mg_kg_max: 25,
    dose_mg_kg_typical: 15,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/6h", "c/8h"],
    default_frequency: "c/6h",
    route: "IV",
    infusion_time: "30-60 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 1,
    renal_adjustment: true,
    notes: "No superar 4 g/día. Ajustar en IR.",
    category: "Carbapenémicos"
  },
  {
    drug_name: "Cefazolina",
    dose_mg_kg_min: 25,
    dose_mg_kg_max: 50,
    dose_mg_kg_typical: 25,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/8h", "c/6h"],
    default_frequency: "c/8h",
    route: "IV",
    infusion_time: "30 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 2,
    renal_adjustment: true,
    notes: "Primera línea para profilaxis quirúrgica.",
    category: "Cefalosporinas 1G"
  },
  {
    drug_name: "Ceftriaxona",
    dose_mg_kg_min: 50,
    dose_mg_kg_max: 100,
    dose_mg_kg_typical: 50,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/12h", "c/24h"],
    default_frequency: "c/24h",
    route: "IV",
    infusion_time: "30 min",
    diluent: "SG 5%",
    volume_ml: 100,
    max_dose_g: 4,
    renal_adjustment: false,
    notes: "No mezclar con calcio en neonatos.",
    category: "Cefalosporinas 3G"
  },
  {
    drug_name: "Cefepime",
    dose_mg_kg_min: 50,
    dose_mg_kg_max: 100,
    dose_mg_kg_typical: 50,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/8h", "c/12h"],
    default_frequency: "c/8h",
    route: "IV",
    infusion_time: "30 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 2,
    renal_adjustment: true,
    notes: "Espectro ampliado vs Pseudomonas.",
    category: "Cefalosporinas 4G"
  },
  {
    drug_name: "Amikacina",
    dose_mg_kg_min: 15,
    dose_mg_kg_max: 20,
    dose_mg_kg_typical: 15,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/24h"],
    default_frequency: "c/24h",
    route: "IV",
    infusion_time: "60 min",
    diluent: "SSN 0.9%",
    volume_ml: 250,
    max_dose_g: 1.5,
    renal_adjustment: true,
    notes: "Monitorear niveles séricos y función renal.",
    category: "Aminoglucósidos"
  },
  {
    drug_name: "Gentamicina",
    dose_mg_kg_min: 5,
    dose_mg_kg_max: 7,
    dose_mg_kg_typical: 5,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/24h", "c/8h"],
    default_frequency: "c/24h",
    route: "IV",
    infusion_time: "30-60 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 0.5,
    renal_adjustment: true,
    notes: "Dosis única diaria preferida. Monitorear audición y función renal.",
    category: "Aminoglucósidos"
  },
  {
    drug_name: "Ciprofloxacino",
    dose_mg_kg_min: 10,
    dose_mg_kg_max: 15,
    dose_mg_kg_typical: 10,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/12h", "c/8h"],
    default_frequency: "c/12h",
    route: "IV",
    infusion_time: "60 min",
    diluent: "SSN 0.9%",
    volume_ml: 200,
    max_dose_g: 0.4,
    renal_adjustment: true,
    notes: "Máximo 400 mg/dosis.",
    category: "Fluoroquinolonas"
  },
  {
    drug_name: "Levofloxacino",
    dose_mg_kg_min: 7,
    dose_mg_kg_max: 10,
    dose_mg_kg_typical: 7.5,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/24h", "c/12h"],
    default_frequency: "c/24h",
    route: "IV",
    infusion_time: "60 min",
    diluent: "SSN 0.9%",
    volume_ml: 150,
    max_dose_g: 0.75,
    renal_adjustment: true,
    notes: "Máximo 750 mg/dosis.",
    category: "Fluoroquinolonas"
  },
  {
    drug_name: "Metronidazol",
    dose_mg_kg_min: 7.5,
    dose_mg_kg_max: 15,
    dose_mg_kg_typical: 7.5,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/8h", "c/6h"],
    default_frequency: "c/8h",
    route: "IV",
    infusion_time: "60 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 0.5,
    renal_adjustment: false,
    notes: "Máximo 500 mg/dosis. Anaerobiocida.",
    category: "Nitroimidazoles"
  },
  {
    drug_name: "Fluconazol",
    dose_mg_kg_min: 6,
    dose_mg_kg_max: 12,
    dose_mg_kg_typical: 6,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/24h"],
    default_frequency: "c/24h",
    route: "IV",
    infusion_time: "60 min",
    diluent: "SSN 0.9%",
    volume_ml: 200,
    max_dose_g: 0.8,
    renal_adjustment: true,
    notes: "Ajustar en IR. Verificar interacciones.",
    category: "Antifúngicos"
  },
  {
    drug_name: "Micafungina",
    dose_mg_kg_min: 1,
    dose_mg_kg_max: 3,
    dose_mg_kg_typical: 1.5,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/24h"],
    default_frequency: "c/24h",
    route: "IV",
    infusion_time: "60 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 0.15,
    renal_adjustment: false,
    notes: "Equinocandina. No requiere ajuste renal.",
    category: "Antifúngicos"
  },
  {
    drug_name: "Aciclovir",
    dose_mg_kg_min: 5,
    dose_mg_kg_max: 10,
    dose_mg_kg_typical: 5,
    dose_unit: "mg",
    dose_basis: "mg/kg",
    frequencies: ["c/8h"],
    default_frequency: "c/8h",
    route: "IV",
    infusion_time: "60 min",
    diluent: "SSN 0.9%",
    volume_ml: 100,
    max_dose_g: 0.5,
    renal_adjustment: true,
    notes: "10 mg/kg para encefalitis herpética. Hidratación adecuada.",
    category: "Antivirales"
  }
];

export function calculateAntibioticDose(drug, weight_kg) {
  if (!drug || !weight_kg) return { calculated: 0, minDose: 0, maxDose: 0 };
  const calculated = Math.round(drug.dose_mg_kg_typical * weight_kg * 10) / 10;
  const minDose = Math.round(drug.dose_mg_kg_min * weight_kg * 10) / 10;
  const maxDose = Math.min(
    Math.round(drug.dose_mg_kg_max * weight_kg * 10) / 10,
    (drug.max_dose_g || 9999) * 1000
  );
  return { calculated, minDose, maxDose };
}

export function validateAntibioticDose(prescribed, minDose, maxDose) {
  if (!prescribed || prescribed <= 0) return { isValid: false, message: "Dosis requerida" };
  if (prescribed < minDose) {
    const pct = (((minDose - prescribed) / minDose) * 100).toFixed(1);
    return { isValid: false, message: `Dosis ${pct}% por debajo del mínimo terapéutico (${minDose} mg)` };
  }
  if (prescribed > maxDose) {
    const pct = (((prescribed - maxDose) / maxDose) * 100).toFixed(1);
    return { isValid: false, message: `Dosis ${pct}% por encima del máximo (${maxDose} mg)` };
  }
  return { isValid: true, message: "Dosis dentro del rango terapéutico" };
}